/* Usuários */
INSERT INTO usuarios VALUES
(NULL, 'user', '$2a$10$MZYOt.MJWagXfhtytOlOVOXYetA7fQnyWQjidHW.qgbTfTHdyBe52'),
(NULL, 'dungeonmaster', '$2a$10$ZI4nLiDut1vk8K.Qug22yOH.F5pzpvXLSKIVrNXRYMsZSBDK3S7WC');

/* Roles */
INSERT INTO roles VALUES
(NULL, 'ROLE_USER'),
(NULL, 'ROLE_ADMIN');

INSERT INTO usuarios_roles VALUES
(1, 1),
(2, 1),
(2, 2);

/* Tendências */
INSERT INTO tendencias VALUES
(NULL, 'Leal e Bom', 'LB', 'Leal e Bom é a tendência de criaturas que se pode contar para fazer o que é correto como esperado pela sociedade. Dragões dourados, paladinos e muitos anões são leais e bons.'),
(NULL, 'Neutro e Bom', 'NB', 'Neutro e Bom é a tendência do povo que faz o melhor que pode para ajudar outros de acordo com suas necessidades. Muitos celestiais, alguns gigantes das nuvens, e grande parte dos gnomos são neutros e bons.'),
(NULL, 'Caótico e Bom', 'CB', 'Caótico e Bom é a tendência de criaturas que agem de acordo com sua própria consciência, se importando pouco com as expectativas de outros. Dragões de cobre, muitos elfos e unicórnios são caóticos e bons.'),
(NULL, 'Leal e Neutro', 'LN', 'Leal e Neutro é a tendência dos indivíduos que agem de acordo com as leis tradições ou códigos pessoais. Muitos monges e alguns magos são leais e neutros.'),
(NULL, 'Neutro', 'N', 'Neutro é a tendência dos indivíduos que preferem não se envolver em questões morais e não tomar partido, fazendo o que aparenta ser melhor conforme o momento. O povo lagarto, muitos druidas e diversos humanos são neutros.'),
(NULL, 'Caótico e Neutro', 'CN', 'Caótico e Neutro é a tendência das criaturas que seguem seus caprichos, mantendo sua liberdade pessoal acima de tudo. Muitos bárbaros e ladinos, e alguns bardos, são caóticos e neutros.'),
(NULL, 'Leal e Mau', 'LM', 'Leal e Mau é a tendência das criaturas que conseguem metodicamente tudo o que querem, dentro dos limites de uma tradição, lei ou ordem. Diabos, dragões azuis e hobgoblins são leais e maus.'),
(NULL, 'Neutro e Mau', 'NM', 'Neutro e Mau é a tendência daqueles que farão tudo o que puderem, sem compaixão ou remorso. Muitos drow, alguns gigantes das nuvens e yugoloths são neutros e maus.'),
(NULL, 'Caótico e Mau', 'CM', 'Caótico e Mau é a tendência de criaturas que agem com violência arbitrária, estimulada por sua ganância, ódio ou sede de sangue. Demônios, dragões vermelhos e orcs são caóticos e maus.'),
(NULL, 'Imparcial', 'I', 'Imparcial na verdade não é uma tendência, mas sim, define as criaturas que não tem capacidade racional para realizar escolhas morais ou éticas.');

/* Idiomas */
INSERT INTO idiomas VALUES
(NULL, 'Abissal', 'Demônios', 'Infernal', 'Exótico'),
(NULL, 'Anão', 'Anões', 'Anão', 'Padrão'),
(NULL, 'Celestial', 'Celestiais', 'Celestial', 'Exótico'),
(NULL, 'Comum', 'Humanos', 'Comum', 'Padrão'),
(NULL, 'Dialeto Subterrâneo', 'Devoradores de mente, observadores', 'Sem', 'Exótico'),
(NULL, 'Dracônico', 'Dragões, draconatos', 'Dracônico', 'Exótico'),
(NULL, 'Élfico', 'Elfos', 'Élfico', 'Padrão'),
(NULL, 'Gigante', 'Ogros, gigantes', 'Anão', 'Padrão'),
(NULL, 'Gnômico', 'Gnomos', 'Anão', 'Padrão'),
(NULL, 'Goblin', 'Goblinoides', 'Anão', 'Padrão'),
(NULL, 'Haalflin', 'Halflings', 'Comum', 'Padrão'),
(NULL, 'Infernal', 'Diabos', 'Infernal', 'Exótico'),
(NULL, 'Orc', 'Orcs', 'Anão', 'Padrão'),
(NULL, 'Primordial', 'Elementais', 'Anão', 'Exótico'),
(NULL, 'Silvestre', 'Criaturas feéricas', 'Élfico', 'Exótico'),
(NULL, 'Subcomum', 'Comerciantes do Subterrâneo', 'Élfico', 'Exótico');

/* Atributos */
/*INSERT simples sem definição de colunas*/
INSERT INTO atributos VALUES
(NULL, 'Força', 'FOR', 'Força define o quão capaz você é de esmagar um tomate, ou talvez algo mais duro', 'Força mede potência física, treinamento atlético e quanta força bruta você é capaz de exercer.', 'Um teste de Força representa qualquer tentativa de levantar, empurrar, puxar ou quebrar algo, forçar seu corpo através de um espaço ou outras formas de aplicar força bruta para resolver uma situação. A perícia Atretismo reflete aptidão em certos tipos de testes de Força. \nOutros Testes de Força. O Mestre pode pedir um teste de Força quando você tentar realizar tarefas como as seguintes: \n*Forçar a abertura de uma porta emperrada, trancada ou bloqueada; \n*Livrar-se de amarras; \n*Passar por um túnel muito pequeno; \n*Segurar-se em uma carroça enquanto é arrastado atrás dela; \n*Tombar uma estátua; \n*Impedir uma pedra grande de rolar em terreno íngrime.', 'Você adiciona o seu modificador de Força para jogadas de ataque e dano quando atacando com armas corpo-a-corpo, como uma maça, um machado de guerra ou uma azagaia. Você usa armas corpo-a-corpo para fazer ataques corpo-a-corpo em combates a curta distância e algumas delas podem ser arremessadas para fazer um ataque a distância.');
/*INSERT simples com definição de colunas*/
INSERT INTO atributos(nomeAtributo, abreviacaoAtributo, tomateAtributo, descricaoAtributo, testesDoAtributo, descricaoComplementar) VALUES
('Destreza', 'DES', 'Destreza define o quão capaz você é de desviar de um tomate que jogaram em você, ou até mesmo pegá-lo e jogá-lo de volta', 'Destreza representa sua agilidade, reflexos, coordenação e equilíbrio.', 'Um teste de Destreza pode envolver qualquer tentativa de se mover de forma ágil, rápida ou silenciosa, ou tentar não cair em terreno traiçoeiro. As perícias Acrobacia, Furtividade e Presdigitação refletem aptidão em certos tipos de testes de Destreza. \nOutros Testes de Destreza. O Mestre pode pedir um teste de Destreza quando você tentar realizar tarefas como as seguintes: \n*Controlar uma carroça muito carregada em uma descida íncrime; \n*Conduzir uma carruagem em uma curva fechada; \n*Abrir uma fechadura; \n*Desarmar uma armadilha; \nAmarrar um prisioneiro com segurança; \n*Livrar-se de amarras; \n*Tocar um instrumento de cordas; \n*Fazer um objeto pequeno ou detalhado.', 'Você adiciona o seu modificador de Destreza para as suas jogadas de ataque e dano quando atacando com armas à distância, como uma funda ou arco longo. Você também pode adicionar o seu modificador de Destreza para jogadas de ataque e dano quando estiver atacando com uma arma corpo-a-corpo que tenha a propriedade acuidade, como uma adaga ou rapieira. \nDependendo da armadura que você veste, você pode adicionar parte ou todo o seu modificador de Destreza para a sua Classe de Armadura. \nNo início de todo combate você joga iniciativa através de um teste de Destreza. Iniciativa determina a ordem que as criaturas vão tomar seus turnos no combate.');
/*INSERT múltiplo sem definição de colunas*/
INSERT INTO atributos VALUES
(NULL, 'Constituição', 'CON', 'Constituição define o quão capaz você é de resistir ao mal estar após comer um tomate podre, ou até mesmo não passar mal', 'Constituição mede saúde, resistência e força vital.', 'Testes de Constituição são incomuns e não tem perícia que use teste de Constituição, porque a resistência que esse atributo representa é em grande parte passiva, em vez de envolver um esforço específico por parte do personagem ou monstro. Um teste de Constituição pode indicar a sua tentativa de ir além dos limites normais. \nO Mestre pode pedir por um teste de Constituição quando você tentar realizar tarefas como as seguintes: \n*Segurar sua respiração; \n*Marchar ou trabalhar por horas sem descanso; \n*Ficar sem dormir; \n*Sobreviver sem comida ou água; \n*Beber uma caneca de cerveja de uma só vez.', 'A constituição influencia diretamente nos pontos de vida, veja mais na definição Pontos de Vida.'),
(NULL, 'Inteligência', 'INT', 'Ser inteligênte é saber que o tomate é uma fruta', 'Inteligência mede a acuidade mental, precisão da memória e habilidade de raciocínio.', 'Um teste de Inteligência entra em jogo quando você precisa recorrer à lógica, educação, memória ou raciocínio dedutivo. As perícias Arcanismo, História, Investigação, Natureza e Religião refletem aptidão em certos tipos de testes de Inteligência. \nOutros Testes de Inteligência. O Mestre pode pedir por um teste de Inteligência quando você tentar realizar tarefas como as seguintes: \n*Comunicar-se com uma criatura sem usar palavras; \n*Estimar o valor de um item precioso; \n*Montar um disfarce para se passar por um guarda da cidade; \n*Forjar um documento; \n*Recordar-se sobre um ofício ou comércio; \n*Vencer um jogo de habilidade.', 'Magos usam Inteligência com sua habilidade para conjurar magias, o que ajuda a determinar o CD dos testes de resistência das magias que eles conjuram.');
/*INSERT múltiplo com definição de colunas*/
INSERT INTO atributos(nomeAtributo, abreviacaoAtributo, tomateAtributo, descricaoAtributo, testesDoAtributo, descricaoComplementar) VALUES
('Sabedoria', 'SAB', 'Sabio é aquele que sabe que um tomate não é usado em uma salada de frutas','Sabedoria reflete o quão em sintonia você está com o mundo ao seu redor e representa percepção e intuição.', 'Um teste de Sabedoria pode refletir um esforço para ler a linguagem corporal, entender os sentimentos de alguém, perceber coisas sobre o ambiente ou cuidar de uma pessoa ferida. As perícias Intuição, Lidar com animais, Medicina, Percepção e Sobrevivência refletem aptidão em certos tipos de testes de Sabedoria. \nOutros Testes de Sabedoria. O Mestre pode pedir por um teste de Sabedoria quando você tentar realizar tarefas como as seguintes: \n*Ter um presentimento sobre o que fazer; \n*Discernir se uma criatura aparentemente morta ou viva é um morto-vivo.', 'Clérigos, druidas e patrulheiros usam Sabedoria como sua habilidade para conjurar magias, o que ajuda a determinar a CD dos testes de resistência das magias que eles conjuram.'),
('Carisma', 'CAR', 'Carismático é aquele que consegue vender uma salada de fruta feita com tomates','O Carisma mede sua capacidade de interagir eficientemente com os outros. Ele inclui fatores como confiança e eloquência, e pode representar uma personalidade encantadora ou dominadora.', 'Um teste de Carisma pode surgir quando você tentar influenciar ou entreter os outros, quando você tenta causar uma impressão ou contar uma mentira convincente ou quando você está em uma situação social complicada. As perícias Atuação, Enganação, Intimidação e Persuasão refletem aptidão em certos tipos de testes de Carisma. \nOutros Testes de Carisma. O Mestre pode pedir por um teste de Carisma quando você tentar realizar tarefas como as seguintes: \n*Encontrar a melhor pessoa para conversar sobre notícias, rumores e boatos; \nMisturar-se em uma multidão para descobrir os principais assuntos da conversa.', 'Bardos, bruxos, feiticeiros e paladinos usam Carisma como sua habilidade para conjurar magias, o que ajuda a determinar a CD dos testes de resistência das magias que eles conjuram.');

/* Pericias */
INSERT INTO pericias VALUES
(NULL, 'Acrobacia', 'Um teste de Destreza (Acrobacia) abrange suas tentativas de ficar em pé em situações complicadas, como tentar correr sobre uma camada de gelo, se equilibrar na corda bamba ou ficar em pé no convés de um navio balançando. A Mestre também pode pedir um teste de Destreza (Acrobacia) para checar se você é capaz de realizar acrobacias, incluindo mergulhos, cambalhotas e saltos mortais.', 2),
(NULL, 'Arcanismo', 'Seu teste de Inteligência (Arcanismo) mede seu conhecimento sobre magias, itens mágicos, símbolos sobrenaturais, tradições mágicas, planos de existência e seus habitantes.', 4),
(NULL, 'Atletismo', 'Um teste de Força (Atletismo) abrange as situações difíceis que você encontra escalando, saltando ou nadando. Exemplos incluem as atividades a seguir: \nVocê tenta escalar um penhasco íngrime ou escorregadio, evitar perigos enquanto escala uma parede ou se segurar em uma superfície enquanto algo tenta te derrubar. \nVocê tenta saltar uma distância muito longa ou fazer um salto intermediário com alguma manobra. \nVocê luta para nadar ou boiar em correntes traiçoeiras, ondas agitadas por tempestades ou áreas cheia de algas marinhas espessas. Outra criatura tenta te puxar ou empurar para baixo da água ou interferir em seu nado.', 1),
(NULL, 'Atuação', 'Um teste de Carisma (Atuação) determina o quão capaz você é de entreter uma plateia com um dança, música, atuação, histórias ou outra forma de entreterimento.', 6),
(NULL, 'Enganação', 'Um teste de Carisma (Enganação) determina o quão convincente você consegue ser ao esconder a verdade, seja por palavras ou ações. Esse engano abrange tudo, desde enganar com ambiguidade até contar mentiras descaradas. Situações típicas incluem lidar com um guarda falando de forma rápida e com excesso de informação para confundir, passar a perna em um comerciante, ganhar dinheiro com apostas, atuar em um disfarce, amenizar as suspeitas de alguem com falsas garantias ou manter a cara séria enquanto conta uma mentira descarada.', 6),
(NULL, 'Furtividade', 'Um teste de Destreza (Furtividade) é realizado para tetar se esconder de inimigos, esgueirar-se por guardas, escapar ou aproximar-se sem ser visto ou ouvido.', 2),
(NULL, 'História', 'Seu teste de Inteligência (História) mede sua capacidade de recordar eventos históricos, pessoas lendárias, reinos antigos, disputas passadas, guerras recentes e civilizações perdidas.', 4),
(NULL, 'Intimidação', 'Quando você tenta influenciar alguém através de ameaças, ações hostis e violência física, o Mestre pode pedir um teste de Carisma (Intimidação). Exemplos incluem tentar conseguir informação de um prisioneiro, amedrontar bandidos de um confronto ou usar uma garafa quebrada para fazer um vizir sádico reconsiderar uma decisão.', 6),
(NULL, 'Intuição', 'Um teste de Sabedoria (Intuição) determina se você é capaz de perceber as verdadeiras intuições de uma criatura, como perceber uma mentira ou prever o próximo movimento de alguém. Faze-lo envolve coletar pistas da llinguagem corporal, habitos de fala e mudanças nos maneirismos.', 5),
(NULL, 'Investigação', 'Quando você olha os arredores buscando pistas e faz deduções baseadas nessas pistas, você faz um teste de Inteligência (Investigação). Você pode deduzir a localização de um objeto escondido, discernir pela aparência de uma ferida que tipo de arma a causou ou determinar o ponto mais fraco em um tunel que poderia fazer esse colapsar. Vasculhar pergaminhos antigos em busca de um fragmento escondido de conhecimento também pode pedir um teste de Inteligência (Investigação).', 4),
(NULL, 'Lidar com animais', 'Quando houver duvidas se você consegue acalmar um animal domesticado, impedir uma montaria de se assustar ou determinar as intenções de um animal, o mestre pode pedir um teste de Sabedoria (Lidar com animais). Você também faz um teste de Sabedoria (Lidar com animais) para manter o controle da sua montaria quando fazendo uma manobra arriscada.', 5),
(NULL, 'Medicina', 'Um teste de Sabedoria (Medicina) permite estabilizar um companheiro em situação de morte ou diagnosticar uma doença.', 5),
(NULL, 'Natureza', 'Um teste de Inteligência (Natureza) mede o conhecimento sobre terrenos, plantas, animais, clima e clicos naturais.', 4),
(NULL, 'Percepção', 'Um teste de Sabedoria (Percepção) envolve observar, ouvir ou detectar a presença de algo. Ele mede a consciência geral do que acontece ao seu redor e a acuidade dos sentidos. Por exemplo, você pode tentar ouvir uma conversa que se passa do outro lado de uma porta, espiar por uma janela aberta ou ouvir monstros se movendo furtivamente na floresta. Ou você pode tentar detectar coisas que estão obscurecidas, ou que são fáceis de se passar despercebidas, sejam orcs fazendo uma emboscada na estrada, bandidos escondidos em um beco escuro ou a luz de velas sob uma porta secreta.', 5),
(NULL, 'Persuasão', 'Quando você tenta influenciar alguém ou um grupo através do tato, delicadeza e boa índole, o Mestre pode pedir para você fazer um teste de Carisma (Persuasão). Normalmente, se usa Persuasão quando se age de boa fé, para promover amizades, fazer pedidos cordiais ou exibindo a etiqueta adequada. Exemplos de Persuasão incluem convencer um camareiro a deixar seu grupo ver o rei, negociar a paz entre duas tribos rivais, ou inspirar a multidão de pessoas da cidade', 6),
(NULL, 'Presdigitação', 'Sempre que você tentar fazer um ato de presdigitação ou trapaça manual, como plantar algo em alguem, ou esconder um objeto em si, faça um teste de Destreza (Presdigitação). O Mestre também pode pedir um teste de Destreza (Presdigitação) para determinar se você consegue roubar uma bolsa de moedas de outra pessoa ou pegar algo do bolso de outra pessoa sem ser notado.', 2),
(NULL, 'Religião', 'Um teste de Inteligência (Religião) mede a capacidade de recordar lendas de divindades, rituais, orações, hierarquias religiosas, símbolos sagrados e outras práticas de cultos secretos e instituições religiosas', 4),
(NULL, 'Sobrevivência', 'O Mestre pode pedir um teste de Sabedoria (Sobrevivência) para seguir rastros, caçar, orientar o grupo por terras gélidas desconhecidas, identificar sinais de ursos-coruja vivendo nas proximidades, prever o clima ou evitar arreia movediça e outros perigos naturais.', 5);

/* Tipos de dano */
INSERT INTO tiposDeDano VALUES
(NULL, 'Ácido', 'A baforada corrosiva de um dragão negro e as enzimas dissolventes secretadas por um pudim negro causam dano ácido.'),
(NULL, 'Concussão', 'Ataques de força bruta como martelos, queda, constrição e coisas do tipo causam dano de concussão.'),
(NULL, 'Cortante', 'Espadas, machados e garras de monstros causam dano cortante.'),
(NULL, 'Elétrico', 'A magia relâmpago e a baforada de um dragão azul causam dano elétrico.'),
(NULL, 'Energia', 'É energia mágica pura focada em uma forma danosa. A maioria dos efeitos que causa dano de energia são magias, incluindo mísseis mágicos e arma espiritual.'),
(NULL, 'Fogo', 'Dragões vermelhos sopram fogo e muitas magias conjuram chamas para causar dano de fogo.'),
(NULL, 'Frio', 'O frio infernal da lança do diabo do gelo e a explosão frígida da baforada de um dragão branco causam dano de frio.'),
(NULL, 'Necrótico', 'Dano necrótico é causado por mortos-vivos e magias como toque arrepiante, definha a matéria e até mesmo a alma.'),
(NULL, 'Perfurante', 'Ataques de perfuração e empalação, incluindo lanças e mordidas de monstros, causam dano perfurante.'),
(NULL, 'Psíquico', 'Habilidades mentais como a rajada psiônica de um devorador de mentes causam dano psíquico.'),
(NULL, 'Radiante', 'Dano radiante, causado pela magia de clérigo coluna de chamas ou a arma de um anjo, cauteriza a carne como fogo e sobrecarrega o espírito com poder.'),
(NULL, 'Trovejante', 'O estouro e concussão do som, como os efeitos da magia onda trovejante, causam dano trovejante.'),
(NULL, 'Veneno', 'Ferrões venenosos e gases tóxicos da baforada de um dragão verde causam dano de veneno.');

/* Condições */
INSERT INTO condicoes VALUES
(NULL, 'Agarrado', 'O deslcamento de uma criatura agarrada se torna 0, e ela não pode se beneficiar de qualquer bonûs em seu deslocamento. \nA condição encerra caso a criatura que a agarrou fique incapacitada (veja a condição). \nA condição se encerra se um efeito remover a criatura agarrada do alcance da criatura que a agarrou ou do que causa a condição.'),
(NULL, 'Amedrontado', 'Uma criatura amedrontada sofre desvantagem em testes de habilidade e jogadas de ataque enquanto a fonte do seu medo estiver em sua linha de visão. \nA criatura não pode se mover voluntariamente de forma que a aproxime da fonte do seu medo'),
(NULL, 'Atordoado', 'Uma criatura atordoada está incapacitada (veja a condição), não pde se mover e somente pode falar hesitantemente. \nA criatura falha automaticamente em testes de resistência de Força ou Destreza. \nJogadas de ataque contra a criatura possuem vantagem.'),
(NULL, 'Caído', 'A única opção de movimento que uma criatura caída tem é rastejar, a menos que ela se levante encerrando a condição. \nA criatura sofre desvantagem nas jogadas de ataque. \nUma jogada de ataque contra a criatura possui vantagem se o atacante estiver a 1,5 metro dela. De qualquer outra forma a jogada sofre desvantagem.'),
(NULL, 'Cego', 'Uma criatura cega falha automaticamente em qualquer teste de habilidade que requeira o uso da visão. \nJogadas de ataque contra a criatura possuem vantagem, e os ataques da criatura sofrem desvantagem.'),
(NULL, 'Enfeitiçado', 'Uma criatura enfeitiçada não pode atacar quem a enfeitiçou ou tê-lo como alvo de habilidades ou efeitos mágicos nocivos. \nQuem a enfeitiçou possui vantagem em testes de habilidade feitos para interagir socialmente com a criatura.'),
(NULL, 'Envenenado', 'Uma criatura envenenada sofre desvantagem em jogadas de ataque e testes de habilidade.'),
(NULL, 'Impedido', 'O deslocamento de uma criatura impedida se torna 0, e ela não pode se beneficiar de qualquer bônus em seu deslocamento. \nJogadas de ataque contra a criatura possuem vantagem, e os ataques de ataque da criatura sofrem desvantagem. \nA criatura sofre desvantagem em testes de resistência de Destreza.'),
(NULL, 'Incapacitado', 'Uma criatura incapacitada não pode realizar ações ou reações.'),
(NULL, 'Inconsciente', 'Uma criatura inconsciente está incapacitada (veja a condição), não pode se mover ou falar e não tem ciência de seus arredores. \nA criatura larga tudo que estiver segurando e fica caída. \nA criatura falha automaticamente em testes de resistência de Força ou Destreza. \nJogadas de ataque contra a criatura possuem vantagem. \nQualquer ataque que atinja a criatura é um acerto crítico, se o atacante estiver a 1,5 metro dela.'),
(NULL, 'Invisível', 'Uma criatura invisível é impossível de ser vista sem a ajuda de magia ou sentidos especiais. Para o propósito de se esconder, a criatura é considerada em uma área de escuridão densa. A localização da criatura pode ser detectada por qualquer barulho que ela faça ou rastros que ela deixe. \nJogadas de ataque contra a criatura sofrem desvantagem e os ataques da criatura possuem vantagem.'),
(NULL, 'Paralisado', 'Uma criatura paralisada está incapacitada (veja a condição) e não pode se mover ou falar. \nA criatura falha automaticamente em testes de resistência de Força e Destreza. \nJogadas de ataque contra a criatura possuem vantagem. \nQualquer ataque que atinja a criatura é um acerto crítico, se o atacante estiver a até 1,5 metro dela'),
(NULL, 'Petrificado', 'Uma criatura petrificada está transformada, juntamente com todos os objetos não-mágicos que estiver vestindo ou carregando, em uma substância sólida e inanimada (geralmente pedra). Seu peso é multiplicado por dez, e ela para de envelhecer. \nA criatura está incapacitada (veja a condição), não pode se mover ou falar, e não tem ciência dos seus arredores. \nJogadas de ataque contra a criatura possuem vantagem. \nA criatura falha automaticamente em testes de resistência de Força e Destreza. \nA criatura tem resistência a todos os tipos de dano. \n A criatura é imune a veneno e doenças, embora um veneno ou doneça previamente presente em seu sistema seja apenas suspenso, não neutralizado.'),
(NULL, 'Surdo', 'Uma criatura surda falha automaticamente em qualquer teste de habilidade que requeira o uso de audição'),
(NULL, 'Exaustão', 'Algumas habilidades especiais e perigos ambientais, como fome e exposição prolongada a temperaturas congelantes ou escaldantes, podem impor uma condição especial chamada exaustão. A exaustão é medida em seis níveis. Um efeito pode fazer com que uma criatura sofra um ou mais níveis de exaustão, como especificado na descrição do efeito. \nSe uma criatura que já possui um nível de exaustão sofrer outro efeito que também causa exaustão, o nível atual de exaustão da criatura aumenta em uma quantidade especificada pela descrição do efeito. \nA criatura sofre o efeito do seu nível atual de exaustão mais todos os níveis anteriores. Uma criatura sofrendo o nível 2 de exaustão tem seu deslocamento reduzido pela metade e sofre desvantagem em testes de habilidade. \nUm efeito que remova exaustão reduz seu nível, com todos os efeitos de exaustão desaparecendo se esse nível for reduzido abaixo de 1. \nTerminar um descanso longo reduz a exaustão de uma criatura em 1 nível, contanto que ela também tenha ingerido água e comida.');

/* Níveis de exaustão */
INSERT INTO exaustao VALUES
(NULL, 1, 'Desvantagem em testes de habilidade', 15),
(NULL, 2, 'Deslocamento reduzido à metade', 15),
(NULL, 3, 'Desvantagem nas jogadas de ataque e testes de resistência', 15),
(NULL, 4, 'Máximo de pontos de vida reduzido à metade', 15),
(NULL, 5, 'Deslocamento reduzido à 0', 15),
(NULL, 6, 'Morte', 15);

INSERT INTO talentos VALUES
(NULL, 'Imobilizador', 'Você aprimorou as habilidades necessárias para tirar proveito quando agarrando uma criatura em combate. Você ganha os seguintes benefícios: \nVocê tem vantagem nas jogadas de ataque contra uma criatura que está agarrando. \nVocê pode usar sua ação para tentar imobilizar a criatura que está agarrando. Para isso, realize outro teste da agarrar. Se tiver sucesso, você e a criatura estão IMPEDIDOS até que o agarrão termine', 'Força 13 ou maior');

INSERT INTO definicoes VALUES
(NULL, 'Tendências', 'Uma criatura tipica do jogo tem uma tendência, o que descreve de forma ampla sua moral e atitudes pessoais. A tendência é a combinação de dois fatores: o primeiro é a moral (bom, mau ou neutro), o segundo define o comportamento perante a sociedade e as leis (leal, caótico ou neutro). Dessas combinações surgem as nove possíveis tendências. \nEsses resumos das nove tendências descrevem o comportamento típico de uma criatura que as tenham. Um indivíduo pode variar significantemente desse comportamento típico, poucas pessoas são perfeitamente e consistentemente fiéis aos preceitos de sua tendência. \nPara muitas criaturas pensantes, a tendência é uma escolha moral. Humanos, anões, elfos e outras raças humanoides podem escolher seguir o caminho do bem ou mau, ordem ou caos. De acordo com as lendas, os deuses de tendência boa, ao criar as raças deram a elas livre arbítrio para escolher seus caminhos morais, sabendo que bondade sem liberdade é escravidão. \nAs divindades malignas que criaram outras raças, por sua vez, fizeram essas para os servir. Essas raças tem forte inclinação inata de cooresponder a natureção de seus deuses. A maioria dos orcs compartilham a natureza violenta e selvagem de seus deuses, tendendo ao mau. Mesmo que um orc escolha uma boa tendência ele lutara contra sua tendência inata por toda a sua vida (Até mesmo os meio-orcs sentem uma leve influencia da tendência do deus dos orcs). \nA tendência é uma parte essencial de criaturas celestiais e demoníacas. Um diabo não escolhe ser leal e mau, e não tende a ser leal e mau, mas sim, é leal e mau em sua essência. Se este deixasse de ser leal e mau, deixaria de ser um diabo. \nA maioria das criaturas não tem capacidade racional, logo não tem tendência, elas são imparciais. Essas criaturas são incapazes de fazer escolhas morais ou éticas e agem de acordo com suas naturezas bestiais. Tubarões são predadores selvagens, por exemplo, mas não são maus, eles só não tem tendência.'),
(NULL, 'Idiomas', 'Sua raça indica os idiomas que seu personagem consegue falar por padrão, e seu antecedente pode lhe dar acesso a um ou mais idiomas adicionais de sua escolha. Anote esses em sua ficha de personagem. \nEscolha seus idiomas dentre os padrões, ou que sejam comuns em sua campanha. Com a permissão do mestre você pode escolher um idioma exótico ou secreto, como as gírias de ladrão ou druídico. \nAlguns idiomas são, famílias de idiomas com muitos dialetos. Por exemplo, o idioma Primordial iclui os dialetos Auran, Aquan, Ignan e Terran, um para cada um dos quatro planos elementais. Criaturas que falam diferentes dialetos do mesmo idioma podem se comunicar entre si.'),
(NULL, 'Talentos', 'Um talento representa um dom ou especialidade em uma área que concede ao seu personagem capacidades especiais. Talentos envolvem treinamento, experiência e habilidades além do que uma classe provem. \nEm determiandos níveis, sua classe te concede a característica Incremento no Valor de Habilidade. Usando a regra opcional de talentos, você pode abdicar dessa característica para adquirir um talento a sua escolha em troca. Você só pode escolher cada talento uma vez, a não ser que a descrição do talento diga o contrário. Você deve atender os pré-requisitos especificados no talento para adquiri-lo. Se você perder o pré-requisito, você não pode usar o talento até recuperar o pré-requisito. Por exemplo, o talento Imobilizador requer Força de 13 ou maior. Se sua Força for reduzida para menos de 13, talvez devido uma maldição de enfraquecer, você não pode se beneficiar do talento Imobilizador até que sua Força seja restaurada.'),
(NULL, 'Condições', 'Condições alteram as capacidades de uma criatura de diversas maneiras e podem surgir como resultado de magias, características de classe, ataque de monstros ou outros efeitos. A maioria das condições, como cego, são prejudiciais, mas algumas, como invisível, podem ser vantajosas. \nUma condição dura até seu efeito ser anulado (a condição caido é anulada ao se levantar, por exemplo) ou até a duração especificada no efeito que impôs a condição. \nSe vários efeitos impõe a mesma condição a uma criatura, cada instância tem sua própria duração, mas a condição não tem seus efeitos agravados. Uma criatura ou tem ou não tem uma condição.'),
(NULL, 'Testes de Resistência', 'Um teste de resistência, também chamado de resistnência, representa uma tentativa de resistir a uma magia, armadilha, veneno, doença ou ameaça similar. Normalmente você não decide fazer um teste de resistência, você é forçado a fazer um porque seru personagem ou monstro corre risco de sofrer algum mal. \nPara fazer um teste de resistência, role um d20 e adicione o modificador de atributo apropriado. Por exemplo, você usa o modificador de Destreza para fazer um teste de resistência de Destreza. \nUm teste de resistência pode ser modificado por um bônus ou penalidade situacional e pode ser afetado por vantagem ou desvantagem, conforme determinado pelo Mestre. \nCada classe concede proficiência em ao menos dois testes de resistência. O mago, por exemplo, é proficiente em testes de inteligência e sabedoria. Da mesma forma que proficiência em perícias, proficiência em testes de resistência permite que o personagem adicione o seu bônus de proficiência nos testes de resistência feitos usando um atributo específico. Alguns monstros também tem proficiência em testes de resistência. \nA Classe de Dificuldade do teste de resistência é determinada pelo efeito que o causou. Por exemplo, a CD para um teste de resistência causado por uma magia é determinada pela habilidade de conjuração e bônus de proficiência de quem a conjurou. \nO resultado de um sucesso ou fracasso em um teste de resistência é detalhado no efeito que o causou. Geralmente, um sucesso significa que a criatura não sofre mal ou dano, ou sofre de maneira reduzida, do efeito'),
(NULL, 'Pontos de Vida', 'O seu modificador de Constituição contribui para os seus pontos de vida. Normalmente, você adiciona o seu modificador de Constituição para cada Dado de Vida que você rolar para seus pontos de vida. \nSe o seu modificador de Constituição mudar, os seus pontos de vida máximos mudam também, como se você tivesse esse novo modificador desde o primeiro nível. Por exemplo, se você aumenta o seu valor de Constituição quando atinge o 4º nível e seu modificador de constituição aumenta de +1 para +2, você ajusta o máximo de pontos de vida como se o modificador sempre tivesse sido +2. Então você adiciona 3 pontos de vida pelos três primeiros níveis, e então, faz a rolagem para os pontos de vida do nível 4 usando o novo modificador. Ou se você está no nível 7 e algum efeito reduz seu valor de constituição de modo que reduza seu modificador em 1, seu máximo de pontos de vida será reduzido em 7.');

INSERT INTO regras VALUES
(NULL, 'Inspiração', 'Inspiração é uma regra que o mestre pode usar para recompensar os jogadores por interpretarem o personagem de acordo com os seus traços de personalidade, ideais, vínculos e defeitos. Ao usar a inspiração, você pode usar seu traço de personalidade para ganhar uma vantagem na negociação com o Príncipe dos Mendigos. Ou inspiração pode permitir que você use o vínculo para com a defesa de sua aldeia natal para sobrepujar o efeito de uma magia sobre você. \nO mestre pode escolher dar inspiração por uma variedade de razões. Tipicamente, o mestre da essa recompensa quando você interpreta de acordo com seus traços de personalidade, cedendo às desvantagens presentes em defeitos e vínculos, ou retrata de outra maneira a verdade do seu personagem. O mestre deve dizer como você pode adquirir inspiração durante o jogo. \nVocê tem ou não tem inspiração, você não pode acumular multiplas inspirações para usar posteriromente. \nQuando você tem inspiração, você pode gasta-la quando você faz uma jogada de ataque, teste de resistência ou de habilidade. Gastar a inspiração te concede vantagem na jogada. \nAdicionalmente, se você tem inspiração, você pode recompensar outro jogador por uma boa interpretação, raciocínio inteligente, ou simplesmente por fazer algo emocionante no jogo. Quando outro personagem faz algo que realmente contribui para a história de maneira divertida e interessante, você pode abrir abrir desistir da sua inspiração para da-la ao outro personagem.'),
(NULL, 'Escondendo-se', 'O Mestre decide se as circunstâncias são apropriadas para se esconder. Quando você tenta se esconder, faça um teste de Destreza (Furtividade). Até que você seja descoberto ou pare de se esconder, o resultado desse teste é contestado pelo teste de Sabedoria (Percepção) de qualquer criatura que esteja ativamente buscando sinais da sua presença. \nVocê não consegue se esconder de uma criatura que tenha visão clara de você, e você entrega sua posição se fizer barulho, como dar um grito de aviso ou derrubar um vaso. \nUma criatura invisível sempre pode tentar se esconder. Sinais da sua presença ainda podem ser notados, e essa tem que permanecer em silêncio. \nEm combate, a maioria das criaturas ficam alerta a sinais de perigo ao seus arredores, então se você tentar se aproximar da criatura normalmente ela o verá. Entretanto, em certas circunstâncias, o Mestre pode permitir que você continue escondido enquanto se aproxima de uma criatura distraida, permitindo que você ganhe vantagem em um ataque antes que seja visto. \nPercepção passiva: Quando você se esconde, existe a possibilidade que alguém perceba você mesmo se não estiver procurando ativamente. Para determinar se uma criatura te percebe ou não, o Mestre compara o seu teste de Destreza (Furtividade) com o valor de Sabedoria (Percepção) Passivo, que é igual 10 + o modificador de Sabedoria da criatura, juntamente a quaisquer outros bônus ou penalidades. Se a criatura tiver vantagem, adicione 5, para desvantagem subtraia 5. Por exemplo, se um personagem nível 1, com um bônus de proficiência +2) possui uma sabedoria de 15, modificador +2, e proficiência em percepção, ele ou ela tem um valor de Sabdoria (Percepção) Passiva de 14. \nO que você pode ver? Um dos principais fatores para determinar se você pode encontrar uma criatura ou objeto escondido é o quão bem você pode ver na area, que pode estar levemente ou densamente escurecida.'),
(NULL, 'Erguendo e Carregando', 'Seu valor de Força determina quanto peso você é capaz de suportar. Os termos a seguir definem o que você consegue levantar ou carregar. \nCapacidade de Carga. Sua capacidade de carga é o seu valor de Força multiplicado por 7,5. Esse é o peso, em kg, que você consegue carregar, o que é alto o suficiente para que normalmente a maioria dos personagens não precise se preocupar com isso. \nEmpurrar, Arrastar e Levantar. Você pode empurrar, arrastar e levantar um peso que seja até o dobro da sua capacidade de carga, 15 vezes o seu valor de força. Enquanto empurrando ou arrastando peso maior que sua capacidade de carga seu deslocamento é reduzido para 1,5 metro. \nTamanho e Força. Criaturas grandes podem aguentar mais peso, por outro lado, criaturas pequenas podem carregar menos. Para cada categoria de tamanho acima de Médio, dobre a capacidade de carga da criatura e o quanto ela consegue empurrar, arrastar e levantar. Para uma criatura pequena, reduza esses pesos pela metade.'),
(NULL, 'Variante: Sobrecarga', 'As regras para levantamento e carga são intencionalmente simples. Essa variante é se você está buscando por regras mais detalhadas que determinem como o personagem está prejudicado pelo peso do equipamento. Quando você usar essa variante, ignore a coluna de Força da tabela de armaduras. \nSe você carregar peso que exceda 2,5 vezes o seu valor de Força você está sobrecarregado, o que significa que seu deslocamento é reduzido em 3 metros. \nSe você carregar peso que exceda 5 vezes o seu valor de Força até o limite da sua capacidade de carga você esta com sobrecarga pesada, o que significa que seu deslocamento reduz em 6 metros e você tem desvantagem em testes de habilidade, jogadas de ataque e testes de resistência que usem Força, Destreza ou Constituição.');

INSERT INTO propriedadesArmas VALUES
(NULL, 'Munição', 'Você pode usar uma arma que tenha a propriedade de munição para fazer um ataque a distancia somente se você tem munição para disparar da arma. A cada vez que você atacar com a arma você ira gastar uma munição. Sacar a munição de uma aljava, ou outro recipiente, é parte do ataque, você precisa de uma mão livre para carregar uma arma de uma mão. Ao final do combate você pode gastar um minuto para recuperar metade das munições usadas fazendo uma busca no campo de batalha. \nSe você usar uma arma que tenha a propriedade de munição para fazer um ataque corpo a corpo você a usa como uma arma improvisada, veja sobre armas improvisadas. \nUma funda precisa estar carregada para ser usada desta forma.'),
(NULL, 'Acuidade', 'Quando fazendo um ataque com uma arma que tenha Acuidade, você pode escolher usar seu modificador de Força ou Destreza para fazer as jogadas de ataque e de dano. Você precisa usar o mesmo modificador para ambos.'),
(NULL, 'Pesada', 'Criaturas pequenas tem desvantagem em jogadas de ataque com armas pesadas. O tamanho e volume de uma arma pesada fazem com que ela seja muito grande para que uma criatura pequena a use eficientemente.'),
(NULL, 'Leve', 'Uma arma leve é pequena e fácil de manusear, fazendo dessa ideal para uso quando combatendo com duas armas.'),
(NULL, 'Recarga', 'Devido o tempo necessário para carregar essa arma, você só consegue disparar uma munição dessa quando usar a ação, ação bônus ou reação para o disparo, independente do número de ataques que você possa fazer normalmente.'),
(NULL, 'Distância', 'Uma arma que pode ser usada para fazer ataques a distância tem o alcance entre parenteses após propriedade de Munição ou Arremesso. O alcance tem dois números. O primeiro mostra o alcance normal da arma em metros, o segundo indica o longo alcance da arma. Quando atacando um alvo além do alcance normal você tem desvantagem na jogada dee ataque. Você não pode atacar um alvo além do alcance longo da arma.'),
(NULL, 'Alcance', 'Essa arma adiciona 1,5 metro ao seu alcance quando atacando com ela e também quando determinando seu alcance apra ataques de oportunidade.'),
(NULL, 'Especial', 'Uma arma com a propriedade Especial tem regras diferentes que regem seu uso. Veja detalhadamente na definição de Armas Especiais.'),
(NULL, 'Arremesso', 'Se uma arma tem a propriedade de Arremesso você pode arremessar a arma para fazer um ataque a distância. Se a arma for uma arma corpo-a-corpo você usa o mesmo modificador de habilidade para a rolagem de ataque e de dano que você usaria para um ataque corpo-a-corpo com a arma. Por exemplo, se você arremessar uma machadinha você usa o modificador de Força, mas se você aremessar uma adaga você pode usar Força ou Destreza, porque a adaga tem a propriedade de Acuidade.'),
(NULL, 'Duas mãos', 'Essa arma requer o uso das duas mãos quando você ataca com a mesma.'),
(NULL, 'Versátil', 'Essa arma pode ser usada com uma ou duas mãos. Um valor de dano entre parenteses aparece com a propriedade, o dano de quando a arma é usada com as duas mãos para fazer um ataque corpo-a-corpo.');

INSERT INTO criaturas VALUES
(NULL, 'Griffin', 'humanoide'),
(NULL, 'Jessie', 'humanoide'),
(NULL, 'Choncc', 'monstro'),
(NULL, 'Kleber', 'humanoide'),
(NULL, 'Guaxi', 'besta');

SELECT * FROM usuarios;
SELECT * FROM roles;
SELECT * FROM usuarios_roles;
SELECT * FROM tendencias;
SELECT * FROM idiomas;
SELECT * FROM atributos;
SELECT * FROM pericias;
SELECT * FROM tiposDeDano;
SELECT * FROM condicoes;
SELECT * FROM exaustao;
SELECT * FROM talentos;
SELECT * from definicoes;
SELECT * FROM regras;
SELECT * FROM propriedadesArmas;
SELECT * FROM criaturas;
